[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = UIqFs+me4VT9FHM9EnlKTMo6Gw47OH8WWKBMRZBgVEk=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer1
PublicKey = oeMYNGg+qnu5YAqb86JZRBvVKn4sSy+LGC/2f8ZkORs=
PresharedKey = SfjX7AkFOSOo4qM0f/KoRJsxiynfrIOBVQLqfUHwTa0=
AllowedIPs = 10.13.13.2/32

[Peer]
# peer2
PublicKey = KyjboR+gSIBIYqbE4d110c6Bo8GwrZMQZDs+dmF6UE4=
PresharedKey = dFC3QPtqN+tbW+QdNdSZCmJgPnoNZQgILTIoDjzLajo=
AllowedIPs = 10.13.13.3/32

