version: "3.8"
services:
  # General
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 7203:443/tcp
      - 7202:80/tcp
    volumes:
      - heimdall:/config
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 8000:8000/tcp
      - 9443:9443/tcp
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: -H tcp://agent:9001 --tlsskipverify
  # Networking
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    restart: unless-stopped
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    container_name: cadvisor
    ports:
      - 8082:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    privileged: true
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "1000"
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    privileged: true
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - INFLUXD_LOG_LEVEL=${INFLUXD_LOG_LEVEL}
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8086:8086/tcp
    volumes:
      - influxdb:/var/lib/influxdb2
  # Media
  youtubedl:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl
    restart: unless-stopped
    environment:
      ALLOW_CONFIG_MUTATIONS: "true"
      ytdl_mongodb_connection_string: "mongodb://ytdl-mongo-db:27017"
      ytdl_use_local_db: "true"
      write_ytdl_config: "true"
    ports:
      - 8998:17442
    volumes:
      - ytdl-appdata:/app/appdata
      - ytdl-audio:/app/audio
      - ytdl-video:/app/video
      - ytdl-subscriptions:/app/subscriptions
      - ytdl-users:/app/users
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${CALIBRE_PASSWORD}
      - CLI_ARGS= #optional
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - calibre-config:/config
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    ports:
      - 8083:8083
    volumes:
      - calibre-config:/config
      - calibre-books:/books
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    environment:
      - AUDIOBOOKSHELF_UID=${PUID}
      - AUDIOBOOKSHELF_GID=${PGID}
    ports:
      - 13378:80
    volumes:
      - audiobookshelf-audiobooks:/audiobooks
      - audiobookshelf-config:/config
      - audiobookshelf-metadata:/metadata
  # Home Automation
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 8123:8123
    volumes:
      - homeassistant:/config
    privileged: true
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto-config:/mosquitto/config/
      - mosquitto-log:/mosquitto/log/
      - mosquitto-data:/mosquitto/data/
  esphome:
    image: esphome/esphome:latest
    container_name: esphome
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 6052:6052
      - 6123:6123
    volumes:
      - esphome:/config
    privileged: true
  partdb:
    container_name: partdb
    ports:
      - 3002:80
    volumes:
      - partdb-uploads:/var/www/html/uploads
      - partdb-public_media:/var/www/html/public/media
      - partdb-db:/var/www/html/var/db
    restart: unless-stopped
    image: jbtronics/part-db1:latest
    environment:
      # Put SQLite database in our mapped folder. You can configure some other kind of database here too.
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/db/app.db
      - APP_ENV=docker
      - DEFAULT_LANG=en
      - DEFAULT_TIMEZONE=Europe/Berlin
      - BASE_CURRENCY=EUR
      - INSTANCE_NAME=Part-DB
      - ALLOW_ATTACHMENT_DOWNLOADS=1
      - USE_GRAVATAR=1

volumes:
  homeassistant:
    name: homeassistant
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/homeassistant"
  ytdl-appdata:
    name: ytdl-appdata
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/ytdl/appdata"
  ytdl-audio:
    name: ytdl-audio
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/ytdl/audio"
  ytdl-video:
    name: ytdl-video
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/ytdl/video"
  ytdl-subscriptions:
    name: ytdl-subscriptions
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/ytdl/subscriptions"
  ytdl-users:
    name: ytdl-users
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/ytdl/users"
  calibre-config:
    name: calibre-config
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/calibre/config"
  calibre-books:
    name: calibre-books
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/calibre/books"
  audiobookshelf-audiobooks:
    name: audiobookshelf-audiobooks
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/audiobookshelf/audiobooks"
  audiobookshelf-config:
    name: audiobookshelf-config
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/audiobookshelf/config"
  audiobookshelf-metadata:
    name: audiobookshelf-metadata
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/audiobookshelf/metadata"
  esphome:
    name: esphome
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/esphome"
  influxdb:
    name: influxdb
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/influxdb"
  grafana:
    name: grafana
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/grafana"
  portainer:
    name: portainer
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/portainer"
  heimdall:
    name: heimdall
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/heimdall"
  mosquitto-data:
    name: mosquitto-data
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/mosquitto/data"
  mosquitto-log:
    name: mosquitto-log
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/mosquitto/log"
  mosquitto-config:
    name: mosquitto-config
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/mosquitto/config"
  partdb-db:
    name: partdb-db
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/partdb/db"
  partdb-uploads:
    name: partdb-uploads
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/partdb/uploads"
  partdb-public_media:
    name: partdb-public_media
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/partdb/public_media"
  prometheus:
    name: prometheus
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER},rw
      device: ":/mnt/store/nfs/docker-volumes/prometheus"
