version: "3.8"
services:
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    restart: unless-stopped
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    ports:
      - 7203:443/tcp
      - 7202:80/tcp
    restart: unless-stopped
    volumes:
      - ./heimdall:/config
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - INFLUXD_LOG_LEVEL=${INFLUXD_LOG_LEVEL}
      - TZ=${TZ}
    ports:
      - 8086:8086/tcp
    volumes:
      - ./influxdb2:/var/lib/influxdb2
      - ./influxdb2/scripts:/docker-entrypoint-initdb.d
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    container_name: pihole
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
    ports:
      - 4443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 1010:80/tcp
    volumes:
      - ./pihole/DNS:/etc/dnsmasq.d
      - ./pihole:/etc/pihole
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 8000:8000/tcp
      - 9443:9443/tcp
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SERVERURL=dorst.duckdns.org
      - SERVERPORT=51820
      - PEERS=2
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  youtubedl:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl
    environment:
      ALLOW_CONFIG_MUTATIONS: "true"
      ytdl_mongodb_connection_string: "mongodb://ytdl-mongo-db:27017"
      ytdl_use_local_db: "true"
      write_ytdl_config: "true"
    restart: always
    volumes:
      - ./youtubedl/appdata:/app/appdata
      - ./youtubedl/audio:/app/audio
      - ./youtubedl/video:/app/video
      - ./youtubedl/subscriptions:/app/subscriptions
      - ./youtubedl/users:/app/users
    ports:
      - "8998:17442"
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PASSWORD=${CALIBRE_PASSWORD}
      - CLI_ARGS= #optional
    volumes:
      - ./calibre/config:/config
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./calibre/config:/config
      - ./calibre/config/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
