version: "3.8"
services:
  # General
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 7203:443/tcp
      - 7202:80/tcp
    volumes:
      - ${VOLUMES}/heimdall:/config
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 8000:8000/tcp
      - 9443:9443/tcp
    volumes:
      - ${VOLUMES}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
  # Networking
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    restart: unless-stopped
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  # Media
  youtubedl:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl
    restart: unless-stopped
    environment:
      ALLOW_CONFIG_MUTATIONS: "true"
      ytdl_mongodb_connection_string: "mongodb://ytdl-mongo-db:27017"
      ytdl_use_local_db: "true"
      write_ytdl_config: "true"
    ports:
      - 8998:17442
    volumes:
      - ${VOLUMES}/ytdl/appdata:/app/appdata
      - ${VOLUMES}/ytdl/audio:/app/audio
      - ${VOLUMES}/ytdl/video:/app/video
      - ${VOLUMES}/ytdl/subscriptions:/app/subscriptions
      - ${VOLUMES}/ytdl/users:/app/users
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${CALIBRE_PASSWORD}
      - CLI_ARGS= #optional
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ${VOLUMES}/calibre/config:/config
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    ports:
      - 8083:8083
    volumes:
      - ${VOLUMES}/calibre/config:/config
      - ${VOLUMES}/calibre/books:/books
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    environment:
      - AUDIOBOOKSHELF_UID=${PUID}
      - AUDIOBOOKSHELF_GID=${PGID}
    ports:
      - 13378:80
    volumes:
      - ${VOLUMES}/audiobookshelf/audiobooks:/audiobooks
      - ${VOLUMES}/audiobookshelf/config:/config
      - ${VOLUMES}/audiobookshelf/metadata:/metadata
  # Home Automation
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 8123:8123
    volumes:
      - ${VOLUMES}/homeassistant:/config
    privileged: true
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${VOLUMES}/mosquitto/config:/mosquitto/config/
      - ${VOLUMES}/mosquitto/log:/mosquitto/log/
      - ${VOLUMES}/mosquitto/data:/mosquitto/data/
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "1000"
    ports:
      - 3000:3000
    volumes:
      - ${VOLUMES}/grafana:/var/lib/grafana
    privileged: true
  esphome:
    image: esphome/esphome:latest
    container_name: esphome
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 6052:6052
      - 6123:6123
    volumes:
      - ${VOLUMES}/esphome:/config
    privileged: true
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - INFLUXD_LOG_LEVEL=${INFLUXD_LOG_LEVEL}
      - TZ=${TZ}
    ports:
      - 8086:8086/tcp
    volumes:
      - ${VOLUMES}/influxdb:/var/lib/influxdb2
