version: "3.8"
services:
  youtubedl:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl
    restart: unless-stopped
    environment:
      ALLOW_CONFIG_MUTATIONS: "true"
      ytdl_mongodb_connection_string: "mongodb://ytdl-mongo-db:27017"
      ytdl_use_local_db: "true"
      write_ytdl_config: "true"
    ports:
      - 8998:17442
    volumes:
      - ytdl-appdata:/app/appdata
      - ytdl-audio:/app/audio
      - ytdl-video:/app/video
      - ytdl-subscriptions:/app/subscriptions
      - ytdl-users:/app/users
  ytdl-mongo-db:
    image: mongo:4.4.18
    container_name: mongo-db
    restart: unless-stopped
    logging:
      driver: "none"
    volumes:
      - ytdl-db:/data/db
