services:
  caddy:
    container_name: caddy
    build: .
    image: caddy:custom
    env_file:
      - .env
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy
      - ./site:/srv
      # mount adventurelog media so Caddy can serve protected media via X-Accel-Redirect
      - /mnt/server/misc/adventure-log/media:/srv/media:ro
      - data:/data
      - config:/config
    networks:
      - caddy
networks:
  caddy:
    external: true
    name: caddy
volumes:
  data:
  config:
