services:
  netbird-client:
      image: netbirdio/netbird:latest
      container_name: netbird-client
      hostname: docker-homelab
      restart: always
      cap_add:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
      network_mode: host
      environment:
          - NB_SETUP_KEY=${NB_SETUP_KEY}
      volumes:
          - netbird-client:/var/lib/netbird
volumes:
  netbird-client:
      name: netbird-client
