name: spliit
services:
  db:
    image: 'postgres:16.3-alpine'
    container_name: spliit-db
    restart: unless-stopped
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: 
        ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 30s
      timeout: 10s
      retries: 5
  spliit:
    image: 'crazymax/spliit:latest'
    container_name: spliit
    depends_on:
      - db
    environment:
      - TZ=${TZ}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    ports:
      - '3001:3000'
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - default
      - caddy

networks:
  caddy:
    name: caddy
    external: true

volumes:
  db: