version: '3.1'
services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: always
    expose:
      - '53'
      - '53/udp'
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
      - './config:/etc/coredns'
    command: -conf /etc/coredns/Corefile
    networks:
      - caddy
networks:
  caddy:
    external: true
    name: caddy