version: "3.8"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: "yobasystems/alpine-mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "nginx"
      MYSQL_DATABASE: "nginx"
      MYSQL_USER: "nginx"
      MYSQL_PASSWORD: "nginx"
    volumes:
      - ./data/mysql:/var/lib/mysql
