[Interface]
Address = 10.13.13.3
PrivateKey = 2JhYymjcazDhC20lxpVQv1hFgrXXc2OWTI2FGvOjGW0=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = Op9dSzVzkF/FExw8SXnGUfL+y9q4/3nmw+1A+UR/pAc=
PresharedKey = dFC3QPtqN+tbW+QdNdSZCmJgPnoNZQgILTIoDjzLajo=
Endpoint = dorst.duckdns.org:51820
AllowedIPs = 0.0.0.0/0
