version: "3.8"

services:
  minecraft:
    container_name: mc-litv3
    image: itzg/minecraft-server:java8-jdk
    ports:
      - 25565:25565
    volumes:
      - mc:/data
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_SLUG: "life-in-the-village-3"
      MEMORY: "10G"
      STOP_SERVER_ANNOUNCE_DELAY: "30"
      CF_FILENAME_MATCHER: "1.5b"
      TZ: "Europe/Berlin"
volumes:
  mc:
    name: mc-litv3
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=truenas,rw
      device: ":/mnt/store/nfs/docker-volumes/mc/life-in-the-village-3"
