services:
  partdb:
    container_name: partdb
    restart: unless-stopped
    ports:
      - '3007:80'
    volumes:
      - uploads:/var/www/html/uploads
      - public_media:/var/www/html/public/media
      - db:/var/www/html/var/db
      - cache:/var/www/html/var/cache
    image: jbtronics/part-db1:latest
    env_file:
      - .env
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80/'
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - caddy

networks:
  caddy:
    name: caddy
    external: true

volumes:
  uploads:
  public_media:
  db:
  cache: