pageInfo:
  title: Home Lab Dashboard
sections:
  - name: Internal Services
    icon: far fa-cloud
    items:
      - title: Speedserver
        description: Proxmox Host
        icon: fas fa-server
        url: http://speedserver:8006
      - title: Truenas
        description: NAS Management
        icon: fas fa-hdd
        url: http://http://192.168.178.201
      - title: Vaultwarden
        description: Password Manager
        icon: fas fa-key
        url: https://vaultwarden.rdorst.dev
      - title: Dockhand
        description: Docker Management
        icon: fab fa-docker
        url: https://docker.rdorst.dev
      - title: Immich
        description: Photo Management
        icon: fas fa-images
        url: https://immich.rdorst.dev
      - title: Affine
        description: Knowledge Base
        icon: fas fa-book
        url: https://affine.rdorst.dev
      - title: Audiobookshelf
        description: Audiobook Server
        icon: fas fa-headphones
        url: https://audio.rdorst.dev
      - title: PartDB
        description: Parts Inventory
        icon: fas fa-cogs
        url: https://parts.rdorst.dev
      - title: Adventure Log
        description: Travel Journal Frontend
        icon: fas fa-map-marked-alt
        url: https://travel.rdorst.dev
      - title: Donetick
        description: To-Do List
        icon: fas fa-tasks
        url: https://todo.rdorst.dev
      - title: Uptime Kuma
        description: Uptime Monitoring
        icon: fas fa-heartbeat
        url: https://uptime.rdorst.dev
      - title: Spliit
        description: Bill Splitting
        icon: fas fa-divide
        url: https://spliit.rdorst.dev
      - title: Dockge Truenas
        description: Docker Compose on Truenas
        icon: fab fa-docker
        url: http://192.168.178.201:31014/
      - title: Home Assistant
        description: Home Automation
        icon: fas fa-home
        url: https://home.rdorst.dev
      - title: Paperless
        description: Document Management
        icon: fas fa-file-alt
        url: https://papers.rdorst.dev
  - name: External Tools
    icon: fas fa-toolbox
    items:
      - title: IT Tools
        description: All-in-one developer toolbox
        icon: fas fa-wrench
        url: https://it-tools.tech/
      - title: Vert
        description: Terminal tools in your browser
        icon: fas fa-terminal
        url: https://vert.sh/
      - title: Webpifier
        description: Convert images to WebP
        icon: fas fa-image
        url: https://www.webpifier.com/
      - title: Cloudflare Dashboard
        description: Manage Cloudflare services
        icon: fab fa-cloudflare
        url: https://one.dash.cloudflare.com/
      - title: BentoPDF
        description: PDF Tools in your browser
        icon: fas fa-file-pdf
        url: https://bentopdf.com/
